CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Tarefas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Titulo" character varying(150) NOT NULL,
    "Descricao" text NOT NULL,
    "Prioridade" character varying(30) NOT NULL,
    "Status" character varying(30) NOT NULL,
    "Dificuldade" character varying(30) NOT NULL,
    "DataInicio" timestamp with time zone,
    "DataTermino" timestamp with time zone,
    "Prazo" timestamp with time zone,
    CONSTRAINT "PK_Tarefas" PRIMARY KEY ("Id")
);

CREATE TABLE "Usuarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Email" character varying(150) NOT NULL,
    "Senha" character varying(255) NOT NULL,
    "Cargo" character varying(30) NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
);

CREATE TABLE "TarefaResponsaveis" (
    "tarefaId" integer NOT NULL,
    "usuarioId" integer NOT NULL,
    CONSTRAINT "PK_TarefaResponsaveis" PRIMARY KEY ("tarefaId", "usuarioId"),
    CONSTRAINT "FK_TarefaResponsaveis_Tarefas_tarefaId" FOREIGN KEY ("tarefaId") REFERENCES "Tarefas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TarefaResponsaveis_Usuarios_usuarioId" FOREIGN KEY ("usuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TarefaResponsaveis_usuarioId" ON "TarefaResponsaveis" ("usuarioId");

CREATE UNIQUE INDEX "IX_Usuarios_Email" ON "Usuarios" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260511210024_Initial', '9.0.15');

COMMIT;

